// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"github.com/goplus/yap/ytest"
	"testing"
)

type App struct {
	ytest.App
}

func (this *App) MainEntry() {
}
func TestMain(m *testing.M) {
	ytest.Gopt_App_TestMain(new(App), m)
}
