// Code generated by gop (Go+); DO NOT EDIT.

package main

import "fmt"

const _ = true
//line use.gop:1
func main() {
//line use.gop:1:1
	n := &N{}
//line use.gop:2:1
	n.OnKey__0("hello", func() {
//line use.gop:3:1
		fmt.Println("hello world")
	})
//line use.gop:5:1
	n.OnKey__1("hello", func(key string) {
//line use.gop:6:1
		fmt.Println(key)
	})
}
