// Code generated by gop (Go+); DO NOT EDIT.

package def

const GopPackage = true
const _ = true
const Gopo_Mul = "MulInt,,MulFloat"
//line def/def.gop:3:1
func MulInt(a int, b int) int {
//line def/def.gop:4:1
	return a * b
}
//line def/def.gop:13:1
func Mul__1(a string, b string) string {
//line def/def.gop:14:1
	return a + b
}
//line def/def.gop:7:1
func MulFloat(a float64, b float64) float64 {
//line def/def.gop:8:1
	return a * b
}
