// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap/ytest"
	"github.com/qiniu/x/stringutil"
	"testing"
)

type case_foo struct {
	ytest.CaseApp
	*App
}
type App struct {
	ytest.App
}
//line main_ytest.gox:1
func (this *App) MainEntry() {
//line main_ytest.gox:1:1
	fmt.Println("hello")
}
//line foo_ytest.gox:1
func (this *case_foo) Main() {
//line foo_ytest.gox:1:1
	this.Mock("foo.com", new(AppV2))
//line foo_ytest.gox:3:1
	id := "123"
//line foo_ytest.gox:4:1
	this.Get(stringutil.Concat("http://foo.com/p/", id))
//line foo_ytest.gox:5:1
	this.RetWith(200)
//line foo_ytest.gox:6:1
	this.Json(map[string]string{"id": id})
}
func (this *case_foo) Classfname() string {
	return "foo"
}
func Test_foo(t *testing.T) {
	ytest.Gopt_CaseApp_TestMain(new(case_foo), t)
}
func TestMain(m *testing.M) {
	ytest.Gopt_App_TestMain(new(App), m)
}
