// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"hello/def"
)

const _ = true
//line use.gop:3
func main() {
//line use.gop:3:1
	fmt.Println(def.MulInt(2, 2))
//line use.gop:4:1
	fmt.Println(def.Mul__1("a", "b"))
}
