// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/spx"

const _ = true

type Jaime struct {
	spx.Sprite
	*Game
}
type Kai struct {
	spx.Sprite
	*Game
}
type Game struct {
	spx.Game
}
//line Jaime.spx:1
func (this *Jaime) Main() {
//line Jaime.spx:1:1
	this.OnMsg__1("1", func() {
//line Jaime.spx:2:1
		this.Say("I come from England.", 2)
//line Jaime.spx:3:1
		this.Broadcast__0("2")
	})
//line Jaime.spx:6:1
	this.OnMsg__1("3", func() {
//line Jaime.spx:7:1
		this.Say("It's mild, but it's not always pleasant.", 4)
//line Jaime.spx:8:1
		this.NextCostume()
//line Jaime.spx:9:1
		this.Say("The weather's often cold in the North and windy in the East.", 5.5)
//line Jaime.spx:10:1
		this.Say("It's often wet in the West and sometimes warm in the South.", 5)
//line Jaime.spx:11:1
		this.Broadcast__0("4")
	})
//line Jaime.spx:14:1
	this.OnMsg__1("5", func() {
//line Jaime.spx:15:1
		this.NextCostume()
//line Jaime.spx:16:1
		this.Say("I like spring and summer.", 2)
//line Jaime.spx:17:1
		this.Say("The days are long and the nights are short.", 3)
//line Jaime.spx:18:1
		this.Say("The sun rises early and sets late. ", 3)
//line Jaime.spx:19:1
		this.NextCostume()
//line Jaime.spx:20:1
		this.Say("I don't like autumn and winter.", 3)
//line Jaime.spx:21:1
		this.Say("The days are short and the nights are long.", 4)
//line Jaime.spx:22:1
		this.Say("The sun rises late and sets early.", 4)
//line Jaime.spx:23:1
		this.NextCostume()
//line Jaime.spx:24:1
		this.Say("Our climate is not very good, but it's certainly interesting.", 5)
//line Jaime.spx:25:1
		this.Say("It's our favourite subject of conversation.", 4)
//line Jaime.spx:26:1
		this.Broadcast__0("6")
	})
//line Jaime.spx:29:1
	this.OnMsg__1("7", func() {
//line Jaime.spx:30:1
		this.Say("Bye!", 2)
//line Jaime.spx:31:1
		this.NextCostume()
	})
}
func (this *Jaime) Classfname() string {
	return "Jaime"
}
//line Kai.spx:1
func (this *Kai) Main() {
//line Kai.spx:1:1
	this.OnStart(func() {
//line Kai.spx:2:1
		this.Say("Where do you come from?", 2)
//line Kai.spx:3:1
		this.Broadcast__0("1")
	})
//line Kai.spx:6:1
	this.OnMsg__1("2", func() {
//line Kai.spx:7:1
		this.Say("What's the climate like in your country?", 3)
//line Kai.spx:8:1
		this.Broadcast__0("3")
	})
//line Kai.spx:11:1
	this.OnMsg__1("4", func() {
//line Kai.spx:12:1
		this.Say("Which seasons do you like best?", 3)
//line Kai.spx:13:1
		this.Broadcast__0("5")
	})
//line Kai.spx:16:1
	this.OnMsg__1("6", func() {
//line Kai.spx:17:1
		this.Say("Thanks. Bye!", 2)
//line Kai.spx:18:1
		this.NextCostume()
//line Kai.spx:19:1
		this.Broadcast__0("7")
	})
}
func (this *Kai) Classfname() string {
	return "Kai"
}
func (this *Game) Main() {
	spx.Gopt_Game_Main(this, new(Jaime), new(Kai))
}
func main() {
	new(Game).Main()
}
