// Code generated by gop (Go+); DO NOT EDIT.

package main

import "fmt"

const _ = true
//line def.gop:2:1
func add__0(a int, b int) int {
//line def.gop:3:1
	return a + b
}
//line def.gop:5:1
func add__1(a string, b string) string {
//line def.gop:6:1
	return a + b
}
//line use.gop:1
func main() {
//line use.gop:1:1
	fmt.Println(add__0(100, 7))
}
