// Code generated by gop (Go+); DO NOT EDIT.

package main

const _ = true
const Gopo_mul = "mulInt,,mulFloat"
//line def.gop:1:1
func mulInt(a int, b int) int {
//line def.gop:2:1
	return a * b
}
//line def.gop:11:1
func mul__1(a string, b string) string {
//line def.gop:12:1
	return a + b
}
//line def.gop:5:1
func mulFloat(a float64, b float64) float64 {
//line def.gop:6:1
	return a * b
}
//line test.gop:1
func main() {
//line test.gop:1:1
	a := 1231
//line test.gop:2:1
	_ = a
}
