// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type get struct {
	yap.Handler
	*AppV2
}
type AppV2 struct {
	yap.AppV2
}
//line get.yap:1
func (this *get) Main(_gop_arg0 *yap.Context) {
	this.Handler.Main(_gop_arg0)
//line get.yap:1:1
	this.Html__1(`<html><body>Hello, YAP!</body></html>`)
}
func (this *get) Classfname() string {
	return "get"
}
func (this *AppV2) Main() {
	yap.Gopt_AppV2_Main(this, new(get))
}
func main() {
	new(AppV2).Main()
}
