// Code generated by gop (Go+); DO NOT EDIT.

package main

import "fmt"

const _ = true

type Foo struct {
}

const Gopo_Foo_Division = ".DivisionInt,.DivisionFoo"
//line def.gop:4:1
func (a *Foo) DivisionInt(b int) *Foo {
//line def.gop:5:1
	fmt.Println("DivisionInt")
//line def.gop:6:1
	return a
}
//line def.gop:9:1
func (a *Foo) DivisionFoo(b *Foo) *Foo {
//line def.gop:10:1
	fmt.Println("DivisionFoo")
//line def.gop:11:1
	return a
}
//line use.gop:1
func main() {
//line use.gop:1:1
	f := &Foo{}
//line use.gop:2:1
	f.DivisionInt(1)
//line use.gop:3:1
	f.DivisionFoo(f)
}
