// Code generated by gop (Go+); DO NOT EDIT.

package main

import "fmt"

const _ = true

type Foo struct {
}

const Gopo_Foo_Division = ".DivisionInt,.DivisionFoo"
//line AaaaAaaa.gop:46:1
func (a *Foo) DivisionInt(b int) *Foo {
//line AaaaAaaa.gop:47:1
	fmt.Println("DivisionInt")
//line AaaaAaaa.gop:48:1
	return a
}
//line AaaaAaaa.gop:51:1
func (a *Foo) DivisionFoo(b *Foo) *Foo {
//line AaaaAaaa.gop:52:1
	fmt.Println("DivisionFoo")
//line AaaaAaaa.gop:53:1
	return a
}

var b *Foo
//line AaaaAaaa.gop:63
func main() {
//line AaaaAaaa.gop:63:1
	b.DivisionInt(1)
}
