// Code generated by gop (Go+); DO NOT EDIT.

package main

import "fmt"

const _ = true
const Gopo_mul = "mulInt,,mulFloat"
//line ../overload-2/def.gop:1:1
func mulInt(a int, b int) int {
//line ../overload-2/def.gop:2:1
	return a * b
}
//line ../overload-2/def.gop:11:1
func mul__1(a string, b string) string {
//line ../overload-2/def.gop:12:1
	return a + b
}
//line ../overload-2/def.gop:5:1
func mulFloat(a float64, b float64) float64 {
//line ../overload-2/def.gop:6:1
	return a * b
}
//line ../overload-2/use.gop:1
func main() {
//line ../overload-2/use.gop:1:1
	fmt.Println(mulInt(100, 7))
//line ../overload-2/use.gop:2:1
	fmt.Println(mulFloat(1.2, 3.14))
//line ../overload-2/use.gop:3:1
	fmt.Println(mulFloat(1.2, 3.14))
//line ../overload-2/use.gop:4:1
	fmt.Println(mul__1("Hello", "World"))
//line ../overload-2/use.gop:5:1
	fmt.Println(mul__1("Hello", "World"))
}
