// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/spx"

const _ = true

type Arrow struct {
	spx.Sprite
	*Game
}
type Calf struct {
	spx.Sprite
	*Game
	id int
}
type Game struct {
	spx.Game
	gid int
}

func (this *Game) MainEntry() {
}
func (this *Game) Main() {
	spx.Gopt_Game_Main(this, new(Arrow), new(Calf))
}
//line Arrow.spx:1
func (this *Arrow) Main() {
//line Arrow.spx:1:1
	this.OnClick(func() {
//line Arrow.spx:2:1
		this.Broadcast__1("undo", true)
//line Arrow.spx:3:1
		this.gid--
	})
}
func (this *Arrow) Classfname() string {
	return "Arrow"
}
//line Calf.spx:5
func (this *Calf) Main() {
//line Calf.spx:5:1
	this.OnClick(func() {
//line Calf.spx:6:1
		spx.Gopt_Sprite_Clone__0(this)
	})
//line Calf.spx:9:1
	this.OnCloned__1(func() {
//line Calf.spx:10:1
		this.gid++
//line Calf.spx:11:1
		this.id = this.gid
//line Calf.spx:12:1
		this.Step__0(50)
//line Calf.spx:13:1
		this.Say(this.id, 0.5)
	})
//line Calf.spx:16:1
	this.OnMsg__1("undo", func() {
//line Calf.spx:17:1
		if this.id == this.gid {
//line Calf.spx:18:1
			this.Destroy()
		}
	})
}
func (this *Calf) Classfname() string {
	return "Calf"
}
func main() {
	new(Game).Main()
}
